Repository luanti-org/minetest_game, pull requests merged in 2018-09, with the labels that each got.

#2200 Fire: Make flames floodable, remove extinguish ABM
  mods/fire/init.lua
Labels: Feature, One approval, Performance

#2208 safer slab name check
  mods/stairs/init.lua
Labels: >= Two approvals, Bugfix

#2207 New hotbar textures
  mods/player_api/README.txt
  mods/player_api/license.txt
  mods/player_api/textures/gui_hotbar.png
  mods/player_api/textures/gui_hotbar_selected.png
Labels: One approval, Textures

#2209 Fire: Remove ABM active when fire mod disabled
  mods/fire/init.lua
Labels: >= Two approvals, Maintenance, Performance

#2217 Remove cave ice from creative inventory
  mods/default/nodes.lua
Labels: One approval

#2221 map: Use wood group crafting recipe
  mods/map/init.lua
Labels: >= Two approvals, Trivial

#2222 Fence rail only connect to fences. Update map mod README recipe
  mods/default/functions.lua
  mods/map/README.txt
Labels: Bugfix, Documentation, One approval
