Repository luanti-org/minetest_game, pull requests merged in 2018-06, with the labels that each got.

#2135 Biomes: Make beaches snowy in snowy biomes
  mods/default/mapgen.lua
Labels: Mapgen, One approval

#2128 TNT: Raise cost of TNT by adding a TNT stick crafting stage
  mods/tnt/README.txt
  mods/tnt/init.lua
  mods/tnt/license.txt
  mods/tnt/textures/tnt_tnt_stick.png
Labels: Balance, Maintenance, Performance

#2136 Settings: Add missing settings to settingtypes.txt
  minetest.conf.example
  settingtypes.txt
Labels: Bugfix, Documentation, Maintenance, Trivial

#2139 Spawn mod: Also reposition players on respawn
  mods/spawn/init.lua
Labels: Feature, One approval

#2126 disallow beds destroying if used
  game_api.txt
  mods/beds/api.lua
  mods/beds/functions.lua
  mods/beds/init.lua
Labels: >= Two approvals, Bugfix

#2155 Add butterflies mod
  mods/butterflies/README.txt
  mods/butterflies/depends.txt
  mods/butterflies/init.lua
  mods/butterflies/license.txt
  mods/butterflies/textures/butterflies_butterfly_red.png
  mods/butterflies/textures/butterflies_butterfly_red_animated.png
  mods/butterflies/textures/butterflies_butterfly_violet.png
  mods/butterflies/textures/butterflies_butterfly_violet_animated.png
  mods/butterflies/textures/butterflies_butterfly_white.png
  mods/butterflies/textures/butterflies_butterfly_white_animated.png
Labels: Feature, Mapgen, One approval

#2156 Make hidden fireflies floodable
  mods/fireflies/init.lua
Labels: Bugfix, Mapgen, One approval
