Repository luanti-org/minetest_game, pull requests merged in 2018-08, with the labels that each got.

#2191 Pine bush: Do not force-place needles nodes
  mods/default/schematics/pine_bush.mts
Labels: Bugfix, Mapgen, Trivial

#2192 Add 'schematic_tables.txt' document
  schematic_tables.txt
Labels: Documentation, One approval

#2194 New appletree schematic
  mods/default/mapgen.lua
  mods/default/nodes.lua
  mods/default/schematics/apple_tree.mts
  mods/default/schematics/apple_tree_from_sapling.mts
  mods/default/trees.lua
  schematic_tables.txt
Labels: Mapgen, One approval, Schematics

#2196 Add new dirt texture by random-geek
  mods/default/README.txt
  mods/default/license.txt
  mods/default/textures/default_dirt.png
Labels: >= Two approvals, Textures

#2186 Simplify DYE mod
  mods/dye/init.lua
Labels: >= Two approvals, Maintenance

#2202 Simplify WOOL mod
  mods/wool/init.lua
Labels: >= Two approvals, Maintenance

#2199 Rename 'killme' mod to 'game_commands' and add missing files
  mods/game_commands/README.txt
  mods/game_commands/init.lua
  mods/game_commands/license.txt
Labels: >= Two approvals, Maintenance

#2206 Game_api.txt: Update dye documentation
  game_api.txt
Labels: Documentation, Maintenance, One approval
