Repository luanti-org/minetest_game, pull requests merged in 2018-03, with the labels that each got.

#2081 Rename 'subgame' to 'game'
  README.txt
  game_api.txt
Labels: Documentation, One approval, Trivial

#2080 New pine needles texture by Splizard
  mods/default/README.txt
  mods/default/textures/default_pine_needles.png
Labels: >= Two approvals, Textures

#2087 Add names for register_decoration
  mods/default/mapgen.lua
  mods/fireflies/init.lua
  mods/flowers/mapgen.lua
Labels: Mapgen, One approval

#2088 Hide fireflies during day time
  mods/fireflies/init.lua
Labels: Feature, Mapgen, One approval

#2096 Xpanes: Description 'Iron Bar' -> 'Steel Bars'
  mods/xpanes/init.lua
Labels: Bugfix, Maintenance, Trivial

#2098 Add formspec theming, remove sfinv's dependency on default
  game_api.txt
  mods/default/init.lua
  mods/sfinv/README.md
  mods/sfinv/api.lua
  mods/sfinv/depends.txt
Labels: Feature, One approval
