Repository luanti-org/minetest_game, pull requests merged in 2018-12, with the labels that each got.

#2273 Prevent crash if some mod inadvertently allowed doors to rotate.
  mods/doors/init.lua
Labels: Bugfix, One approval

#2274 Remove unused 'puts out fire' group
  mods/default/nodes.lua
  mods/stairs/init.lua
Labels: Maintenance, One approval

#2224 Allow on_rightclick to be overidden
  game_api.txt
  mods/doors/init.lua
Labels: >= Two approvals, Feature

#2276 Doors: New handle and hinges for glass door
  mods/doors/README.txt
  mods/doors/textures/doors_door_glass.png
  mods/doors/textures/doors_item_glass.png
Labels: One approval, Textures
