Repository luanti-org/minetest_game, pull requests merged in 2018-07, with the labels that each got.

#2160 Replace deprecated function calls
  mods/beds/functions.lua
  mods/beds/spawns.lua
  mods/boats/init.lua
  mods/bones/init.lua
  mods/bucket/init.lua
  mods/default/craftitems.lua
  mods/default/item_entity.lua
  mods/dungeon_loot/mapgen.lua
  mods/fire/init.lua
  mods/sethome/init.lua
  mods/stairs/init.lua
  mods/tnt/init.lua
Labels: Maintenance, One approval

#2159 Fix input checking for "Force night skip" (#1964)
  mods/beds/functions.lua
Labels: >= Two approvals, Bugfix

#2140 Boats: Add cruise mode (autoforward)
  mods/boats/README.txt
  mods/boats/init.lua
Labels: Feature, One approval

#2163 Update carts from boost_cart
  mods/carts/cart_entity.lua
  mods/carts/functions.lua
  mods/carts/init.lua
Labels: Feature, Maintenance, One approval

#2158 add fence rails
  mods/default/crafting.lua
  mods/default/functions.lua
  mods/default/nodes.lua
  mods/default/textures/default_fence_rail_overlay.png
  mods/walls/init.lua
Labels: >= Two approvals, Feature

#2162 Boats: Properly use 'dtime' for consistent responsiveness
  mods/boats/init.lua
Labels: Bugfix, Maintenance, One approval

#2172 Remove coral air-death ABM
  mods/default/functions.lua
Labels: One approval, Performance

#2171 Move chests to a new file. Update credits for chests and torches
  mods/default/README.txt
  mods/default/chests.lua
  mods/default/init.lua
  mods/default/nodes.lua
  mods/default/torch.lua
Labels: >= Two approvals, Maintenance

#2173 add evergreen bush
  game_api.txt
  mods/default/README.txt
  mods/default/crafting.lua
  mods/default/mapgen.lua
  mods/default/nodes.lua
  mods/default/schematics/pine_bush.mts
  mods/default/textures/default_pine_bush_sapling.png
  mods/default/textures/default_pine_bush_stem.png
  mods/default/trees.lua
Labels: >= Two approvals, Feature, Mapgen

#2176 Default: Credit schematics and licence as media
  mods/default/README.txt
Labels: Documentation, One approval

#2175 Boats: Use driver name string instead of objectref
  mods/boats/init.lua
Labels: Maintenance, One approval

#2178 Flora spread: Reduce maximum density
  mods/flowers/init.lua
Labels: Bugfix, Maintenance

#2183 Make apple log shorter, to be no longer than appletree trunk
  mods/default/schematics/apple_log.mts
Labels: Maintenance, Mapgen, One approval

#2188 Boats, carts mods: Use 'initial_properties' table
  mods/boats/init.lua
  mods/carts/cart_entity.lua
Labels: Maintenance, Trivial

#2189 sfinv, player_api mods: Fix and cleanup README and license files
  mods/default/README.txt
  mods/player_api/README.txt
  mods/player_api/license.txt
  mods/sfinv/README.md
  mods/sfinv/README.txt
  mods/sfinv/license.txt
Labels: Documentation, Maintenance, Trivial
