Repository luanti-org/minetest_game, pull requests merged in 2018-10, with the labels that each got.

#2219 Stairs: Add field to registration to determine world-aligned textures
  game_api.txt
  mods/farming/nodes.lua
  mods/stairs/init.lua
Labels: Blocker, Bugfix, High priority, One approval

#2229 add glass and obsidian glass stairs
  mods/stairs/README.txt
  mods/stairs/init.lua
  mods/stairs/textures/stairs_glass_outer_stairside.png
  mods/stairs/textures/stairs_glass_split.png
  mods/stairs/textures/stairs_glass_stairside.png
  mods/stairs/textures/stairs_obsidian_glass_outer_stairside.png
  mods/stairs/textures/stairs_obsidian_glass_split.png
  mods/stairs/textures/stairs_obsidian_glass_stairside.png
Labels: >= Two approvals, Feature, Textures

#2180 Add blueberry bushes
  game_api.txt
  mods/default/README.txt
  mods/default/craftitems.lua
  mods/default/mapgen.lua
  mods/default/nodes.lua
  mods/default/schematics/blueberry_bush.mts
  mods/default/textures/default_blueberries.png
  mods/default/textures/default_blueberry_bush_leaves.png
  mods/default/textures/default_blueberry_bush_sapling.png
  mods/default/textures/default_blueberry_overlay.png
  mods/default/trees.lua
  mods/dye/init.lua
  schematic_tables.txt
Labels: >= Two approvals, Feature, Mapgen

#2232 Connect fence rails to walls
  mods/default/functions.lua
Labels: >= Two approvals

#2233 comment out combine slabs code
  mods/stairs/init.lua
Labels: >= Two approvals

#2240 Spawn mod: Avoid respawn conflict with beds mod
  mods/spawn/depends.txt
  mods/spawn/init.lua
Labels: Blocker, Bugfix, One approval

#2245 Fix crash on empty key metadata
  mods/default/chests.lua
Labels: Bugfix, One approval

#2253 Modify Fancy Bed textures
  mods/beds/README.txt
  mods/beds/beds.lua
  mods/beds/license.txt
  mods/beds/textures/beds_bed_under.png
Labels: >= Two approvals, Maintenance, Textures
