Repository luanti-org/minetest_game, pull requests merged in 2018-05, with the labels that each got.

#2073 Biomes: Add tundra lowland with permafrost, stones, moss and snow
  mods/default/README.txt
  mods/default/mapgen.lua
  mods/default/nodes.lua
  mods/default/textures/default_moss.png
  mods/default/textures/default_moss_side.png
  mods/default/textures/default_permafrost.png
  mods/default/textures/default_stones.png
Labels: Feature, Mapgen, One approval, Textures

#2121 Enable regrowth of apples
  mods/default/nodes.lua
Labels: >= Two approvals, Feature

#2120 Biomes: Add vertical biome blends
  mods/default/mapgen.lua
Labels: Feature, Mapgen, One approval

#2130 Kelp: Add 'paramtype = light' to avoid black plantlike extension
  mods/default/nodes.lua
Labels: Bugfix, Trivial

#2131 Place hidden instead of visible fireflies on mapgen
  mods/fireflies/init.lua
Labels: Mapgen, One approval

#2133 Snow: Make players sink in by 3/16 node
  mods/default/nodes.lua
Labels: One approval
