Repository luanti-org/minetest_game, pull requests merged in 2019-03, with the labels that each got.

#2324 Flowers: Remove stack max definition
  mods/flowers/init.lua
Labels: >= Two approvals, Maintenance

#2327 Properly count players in beds.
  mods/beds/functions.lua
Labels: Bugfix, One approval

#2337 Update init.lua
  mods/map/init.lua
Labels: One approval, Trivial

#2335 add food groups to blueberries
  mods/default/craftitems.lua
Labels: >= Two approvals, Maintenance

#2345 Fix beds being undiggable after laying down
  mods/beds/functions.lua
Labels: Bugfix, One approval

#2344 Dungeon loot: Avoid empty 'if' branch to satisfy build checks
  mods/dungeon_loot/mapgen.lua
Labels: Maintenance, Trivial

#2346 Restrict waving liquid shader to normal water
  mods/default/nodes.lua
Labels: Feature, Maintenance, Trivial

#2331 fire: Document flammable group and remove duplicate code
  game_api.txt
  mods/fire/init.lua
Labels: >= Two approvals, Maintenance

#2332 Flowers mod: Light check optimisation in mushroom spread
  mods/flowers/init.lua
Labels: >= Two approvals, Maintenance
