Repository luanti-org/minetest_game, pull requests merged in 2019-01, with the labels that each got.

#2271 Add large cactus seedling
  mods/default/README.txt
  mods/default/crafting.lua
  mods/default/license.txt
  mods/default/mapgen.lua
  mods/default/nodes.lua
  mods/default/schematics/large_cactus.mts
  mods/default/textures/default_large_cactus_seedling.png
  mods/default/trees.lua
  schematic_tables.txt
Labels: Feature, One approval

#2281 Remove extra empty strings in craft recipes
  mods/farming/api.lua
  mods/fireflies/init.lua
  mods/stairs/init.lua
Labels: Maintenance

#2282 Remove uses of default.gui_bg/bg_img/slots
  mods/bones/init.lua
  mods/creative/inventory.lua
  mods/default/chests.lua
  mods/default/craftitems.lua
  mods/default/furnace.lua
  mods/default/init.lua
  mods/default/legacy.lua
  mods/default/nodes.lua
  mods/vessels/init.lua
Labels: >= Two approvals, Maintenance

#2284 Fix small pine leafdecay: New schematics, new leafdecay radius
  mods/default/nodes.lua
  mods/default/schematics/small_pine_tree.mts
  mods/default/schematics/small_pine_tree_from_sapling.mts
  mods/default/schematics/snowy_small_pine_tree_from_sapling.mts
Labels: Blocker, Bugfix, High priority, Maintenance, Trivial

#2285 Update small pines in schematic_tables.txt
  schematic_tables.txt
Labels: >= Two approvals, Blocker, Documentation, High priority, Trivial
