Repository luanti-org/minetest_game, pull requests merged in 2019-06, with the labels that each got.

#2378 Add groups for tools/ores/flowers
  mods/bucket/init.lua
  mods/default/craftitems.lua
  mods/default/tools.lua
  mods/farming/hoes.lua
  mods/flowers/init.lua
  mods/screwdriver/init.lua
Labels: >= Two approvals, Feature

#2383 Fixed Moss-growth-function. Prevents server for crash.
  mods/default/functions.lua
Labels: Bugfix, Maintenance, One approval, Trivial

#2389 Large cactus schematic: Don't force-place root node
  mods/default/schematics/large_cactus.mts
  schematic_tables.txt
Labels: Bugfix, Trivial

#2388 Allow overriding default.after_place_leaves and default.grow_sapling easily
  mods/default/nodes.lua
Labels: Bugfix, One approval

#2349 Add waving waterlily
  mods/flowers/init.lua
  mods/flowers/mapgen.lua
Labels: >= Two approvals, Feature

#2397 Use 9-slice background in formspec theme
  mods/default/init.lua
Labels: Feature, One approval
