Repository luanti-org/minetest_game, pull requests merged in 2019-09, with the labels that each got.

#2460 Turn "README.txt" into the markdown language
  README.md
  README.txt
Labels: >= Two approvals, Documentation, Maintenance

#2461 Update xpanes init.lua
  mods/xpanes/init.lua
Labels: Maintenance, One approval, Trivial

#2466 Add support for MT 5 game translation (rebasing #2368)
  mods/beds/beds.lua
  mods/beds/init.lua
  mods/binoculars/init.lua
  mods/boats/init.lua
  mods/bones/init.lua
  mods/bucket/init.lua
  mods/butterflies/init.lua
  mods/carts/cart_entity.lua
  mods/carts/init.lua
  mods/carts/rails.lua
  mods/creative/init.lua
  mods/creative/inventory.lua
  mods/default/chests.lua
  mods/default/craftitems.lua
  mods/default/furnace.lua
  mods/default/init.lua
  mods/default/nodes.lua
  mods/default/tools.lua
  mods/default/torch.lua
  mods/default/trees.lua
  mods/doors/init.lua
  mods/dye/init.lua
  mods/farming/api.lua
  mods/farming/hoes.lua
  mods/farming/init.lua
  mods/farming/nodes.lua
  mods/fire/init.lua
  mods/fireflies/init.lua
  mods/flowers/init.lua
  mods/game_commands/init.lua
  mods/give_initial_stuff/init.lua
  mods/map/init.lua
  mods/player_api/init.lua
  mods/screwdriver/init.lua
  mods/sethome/init.lua
  mods/sfinv/init.lua
  mods/spawn/init.lua
  mods/stairs/init.lua
  mods/tnt/init.lua
  mods/vessels/init.lua
  mods/walls/init.lua
  mods/wool/init.lua
  mods/xpanes/init.lua
Labels: >= Two approvals, Feature, Translation

#2064 Add initial environmental sounds mod with flowing water sounds
  minetest.conf.example
  mods/env_sounds/README.txt
  mods/env_sounds/init.lua
  mods/env_sounds/license.txt
  mods/env_sounds/mod.conf
  mods/env_sounds/sounds/env_sounds_water.1.ogg
  mods/env_sounds/sounds/env_sounds_water.2.ogg
  mods/env_sounds/sounds/env_sounds_water.3.ogg
  mods/env_sounds/sounds/env_sounds_water.4.ogg
  settingtypes.txt
Labels: Feature, One approval, Sounds

#2477 Add missing infotext to nodes
  mods/default/furnace.lua
  mods/default/nodes.lua
  mods/doors/init.lua
  mods/vessels/init.lua
Labels: Bugfix, One approval

#2462 Tall fences and walls
  minetest.conf.example
  mods/default/functions.lua
  mods/doors/init.lua
  mods/walls/init.lua
  settingtypes.txt
Labels: >= Two approvals, Feature

#2487 Fix more translation strings
  game_api.txt
  mods/beds/functions.lua
  mods/creative/inventory.lua
  mods/default/craftitems.lua
  mods/default/nodes.lua
  mods/farming/api.lua
  mods/farming/init.lua
  mods/farming/nodes.lua
  mods/sfinv/init.lua
Labels: Bugfix, One approval, Translation

#2481 Set fuel percentage to decrease
  mods/default/furnace.lua
Labels: Maintenance, One approval

#2485 Update functions.lua
  mods/default/functions.lua
Labels: >= Two approvals, Maintenance, Trivial

#2492 Fix vessel shelf to vessels shelf in infotext
  mods/vessels/init.lua
Labels: Bugfix, Trivial

#2493 Marram grass: Fix noise flags to make 2D noise 'eased'
  mods/default/mapgen.lua
Labels: Bugfix, Mapgen, One approval, Trivial

#2490 add bar door and trapdoor
  mods/xpanes/README.txt
  mods/xpanes/init.lua
  mods/xpanes/license.txt
  mods/xpanes/mod.conf
  mods/xpanes/textures/xpanes_door_steel_bar.png
  mods/xpanes/textures/xpanes_item_steel_bar.png
  mods/xpanes/textures/xpanes_trapdoor_steel_bar.png
  mods/xpanes/textures/xpanes_trapdoor_steel_bar_side.png
Labels: >= Two approvals, Feature

#2500 Fix glass panes sides
  game_api.txt
  mods/xpanes/init.lua
Labels: Bugfix, Documentation, One approval

#2503 Remove leaf decay/sneak key gotcha'
  mods/default/functions.lua
Labels: >= Two approvals, Bugfix

#2497 xpanes add new steel bar door sounds
  mods/xpanes/README.txt
  mods/xpanes/init.lua
  mods/xpanes/sounds/xpanes_steel_bar_door_close.ogg
  mods/xpanes/sounds/xpanes_steel_bar_door_open.ogg
Labels: >= Two approvals, Sounds
