Repository luanti-org/minetest_game, pull requests merged in 2019-02, with the labels that each got.

#2293 Tweak permafrost and stones textures
  mods/default/README.txt
  mods/default/nodes.lua
  mods/default/textures/default_permafrost.png
  mods/default/textures/default_stones.png
  mods/default/textures/default_stones_side.png
Labels: >= Two approvals, Textures

#2299 Add screenshot.png, and more info to game.conf
  game.conf
  screenshot.png
Labels: Blocker, High priority, One approval

#2295 Remove type="shapeless" from single-item recipes
  mods/dye/init.lua
Labels: Maintenance, One approval, Trivial

#2225 Beds: Improve on_rotate function
  mods/beds/api.lua
Labels: >= Two approvals, Maintenance, Trivial

#2302 Limit sign length to 512 (~6 lines of 80 char or so).
  mods/default/nodes.lua
Labels: Action / change needed, Blocker, Bugfix, High priority, Trivial

#2309 Beds: Do not require red wool to craft beds
  mods/beds/beds.lua
Labels: One approval

#2310 fix sfinv hotbar offset.
  mods/sfinv/init.lua
Labels: Maintenance, One approval, Trivial

#2311 Kelp, coral sounds: Add missing 'footstep'. Use quiet 'dig', 'dug'
  mods/default/nodes.lua
Labels: Bugfix, One approval, Sounds

#2314 Remove corals.mts credit
  mods/default/README.txt
Labels: Documentation, Trivial
