Repository luanti-org/minetest_game, pull requests merged in 2019-08, with the labels that each got.

#2431 mtg mods use " " instead of ' ' for item names
  mods/bucket/init.lua
  mods/doors/init.lua
  mods/dye/init.lua
  mods/farming/nodes.lua
  mods/stairs/init.lua
  mods/walls/init.lua
Labels: Maintenance, One approval, Trivial

#2429 Warn when a mod registers a stairs node with an existing name
  mods/stairs/init.lua
Labels: >= Two approvals

#2433 Make the creative mod hand dig 'dig_immediate' nodes fast
  mods/creative/init.lua
Labels: Bugfix, One approval

#2437 furnace: Fix "output full" infotext
  mods/default/furnace.lua
Labels: Bugfix, One approval

#2439 Sfinv: Add and use a crafting arrow texture instead of default mod furnace arrow
  mods/sfinv/README.txt
  mods/sfinv/init.lua
  mods/sfinv/license.txt
  mods/sfinv/textures/sfinv_crafting_arrow.png
Labels: Maintenance, One approval, Textures

#2447 TNT: Remove unusable sounds, use temporary placeholders
  mods/tnt/sounds/tnt_explode.ogg
  mods/tnt/sounds/tnt_ignite.ogg
Labels: Maintenance, Sounds, Trivial

#2448 Verify object is player before checking privs
  mods/default/functions.lua
Labels: Bugfix, One approval

#2445 furnace: Improve fuel item replacement support
  mods/default/furnace.lua
Labels: >= Two approvals, Maintenance

#2449 add_new_tnt_sounds
  mods/tnt/README.txt
  mods/tnt/init.lua
  mods/tnt/license.txt
  mods/tnt/sounds/tnt_explode.ogg
  mods/tnt/sounds/tnt_gunpowder_burning.ogg
  mods/tnt/sounds/tnt_ignite.ogg
Labels: >= Two approvals, Sounds

#2452 Spawn: Avoid spawning outside small worlds
  mods/spawn/init.lua
Labels: Bugfix, One approval

#2457 Creative: Override the hand instead of re-registering
  mods/creative/init.lua
  mods/creative/mod.conf
Labels: Maintenance, One approval
