Repository luanti-org/minetest_game, pull requests merged in 2019-12, with the labels that each got.

#2543 README: Use correct link, make link clickable
  README.md
Labels: Documentation, Trivial

#2527 Simplify tools crafting registration
  mods/default/crafting.lua
  mods/default/tools.lua
Labels: >= Two approvals, Maintenance

#2549 Convert grass footstep sounds from stereo to mono
  mods/default/sounds/default_grass_footstep.1.ogg
  mods/default/sounds/default_grass_footstep.2.ogg
  mods/default/sounds/default_grass_footstep.3.ogg
Labels: Bugfix, Sounds, Trivial

#2550 Add missing 'weather' mod documentation to minetest.conf.example
  minetest.conf.example
  settingtypes.txt
Labels: Documentation, Trivial

#2544 Remove floatland biome code
  mods/butterflies/init.lua
  mods/default/mapgen.lua
  mods/flowers/mapgen.lua
Labels: Mapgen

#2376 Improved walk animation and stand animation
  mods/player_api/README.txt
  mods/player_api/license.txt
  mods/player_api/models/character.b3d
  mods/player_api/models/character.blend
Labels: >= Two approvals, Maintenance, Models

#2552 rename `core` to `minetest`
  .luacheckrc
  mods/game_commands/init.lua
Labels: Maintenance, One approval, Trivial
