Repository luanti-org/minetest_game, pull requests merged in 2019-10, with the labels that each got.

#2507 Grammar updates README.txt
  mods/beds/README.txt
Labels: Documentation, One approval, Trivial

#2512 Update translation templates and German
  mods/vessels/locale/template.txt
  mods/vessels/locale/vessels.de.tr
  mods/xpanes/locale/template.txt
  mods/xpanes/locale/xpanes.de.tr
Labels: >= Two approvals, Bugfix, Translation

#2514 Add French translation
  mods/beds/locale/beds.fr.tr
  mods/binoculars/locale/binoculars.fr.tr
  mods/boats/locale/boats.fr.tr
  mods/bones/locale/bones.fr.tr
  mods/bucket/locale/bucket.fr.tr
  mods/butterflies/locale/butterflies.fr.tr
  mods/carts/locale/carts.fr.tr
  mods/creative/locale/creative.fr.tr
  mods/default/locale/default.fr.tr
  mods/doors/locale/doors.fr.tr
  mods/dye/locale/dye.fr.tr
  mods/farming/locale/farming.fr.tr
  mods/fire/locale/fire.fr.tr
  mods/fireflies/locale/fireflies.fr.tr
  mods/flowers/locale/flowers.fr.tr
  mods/game_commands/locale/game_commands.fr.tr
  mods/map/locale/map.fr.tr
  mods/screwdriver/locale/screwdriver.fr.tr
  mods/sethome/locale/sethome.fr.tr
  mods/sfinv/locale/sfinv.fr.tr
  mods/stairs/locale/stairs.fr.tr
  mods/tnt/locale/tnt.fr.tr
  mods/vessels/locale/vessels.fr.tr
  mods/walls/locale/walls.fr.tr
  mods/wool/locale/wool.fr.tr
  mods/xpanes/locale/xpanes.fr.tr
Labels: One approval, Translation

#2505 Spanish Translation
  mods/beds/locale/beds.es.tr
  mods/binoculars/locale/binoculars.es.tr
  mods/boats/locale/boats.es.tr
  mods/bones/locale/bones.es.tr
  mods/bucket/locale/bucket.es.tr
  mods/butterflies/locale/butterflies.es.tr
  mods/carts/locale/carts.es.tr
  mods/creative/locale/creative.es.tr
  mods/default/locale/default.es.tr
  mods/doors/locale/doors.es.tr
  mods/dye/locale/dye.es.tr
  mods/farming/locale/farming.es.tr
  mods/fire/locale/fire.es.tr
  mods/fireflies/locale/fireflies.es.tr
  mods/flowers/locale/flowers.es.tr
  mods/game_commands/locale/game_commands.es.tr
  mods/map/locale/map.es.tr
  mods/screwdriver/locale/screwdriver.es.tr
  mods/sethome/locale/sethome.es.tr
  mods/sfinv/locale/sfinv.es.tr
  mods/stairs/locale/stairs.es.tr
  mods/tnt/locale/tnt.es.tr
  mods/vessels/locale/vessels.es.tr
  mods/walls/locale/walls.es.tr
  mods/wool/locale/wool.es.tr
  mods/xpanes/locale/xpanes.es.tr
Labels: One approval, Translation

#2491 Italian localisation
  mods/beds/locale/beds.it.tr
  mods/binoculars/locale/binoculars.it.tr
  mods/boats/locale/boats.it.tr
  mods/bones/locale/bones.it.tr
  mods/bucket/locale/bucket.it.tr
  mods/butterflies/locale/butterflies.it.tr
  mods/carts/locale/carts.it.tr
  mods/creative/locale/creative.it.tr
  mods/default/locale/default.it.tr
  mods/doors/locale/doors.it.tr
  mods/dye/locale/dye.it.tr
  mods/farming/locale/farming.it.tr
  mods/fire/locale/fire.it.tr
  mods/fireflies/locale/fireflies.it.tr
  mods/flowers/locale/flowers.it.tr
  mods/game_commands/locale/game_commands.it.tr
  mods/map/locale/map.it.tr
  mods/screwdriver/locale/screwdriver.it.tr
  mods/sethome/locale/sethome.it.tr
  mods/sfinv/locale/sfinv.it.tr
  mods/stairs/locale/stairs.it.tr
  mods/tnt/locale/tnt.it.tr
  mods/vessels/locale/vessels.it.tr
  mods/walls/locale/walls.it.tr
  mods/wool/locale/wool.it.tr
  mods/xpanes/locale/xpanes.it.tr
Labels: >= Two approvals, Translation

#2515 Increase (ocean) water opacity to 191
  mods/default/nodes.lua
Labels: Feature, One approval, Textures

#2524 Fix duplicate background in formspec prepend.
  mods/default/init.lua
Labels: Maintenance, One approval

#2508 Add initial 'weather' mod to vary cloud density, thickness, velocity
  mods/weather/README.txt
  mods/weather/init.lua
  mods/weather/license.txt
  mods/weather/mod.conf
  settingtypes.txt
Labels: Feature, One approval

#2453 Move hotbar code/textures, and damage sound, from player_api to default
  mods/default/README.txt
  mods/default/init.lua
  mods/default/sounds/player_damage.ogg
  mods/default/textures/gui_hotbar.png
  mods/default/textures/gui_hotbar_selected.png
  mods/player_api/README.txt
  mods/player_api/init.lua
  mods/player_api/license.txt
Labels: Maintenance, Sounds, Textures, Trivial

#2523 Improve creative inventory search
  mods/creative/inventory.lua
Labels: Feature, One approval

#2338 boats: Improve physics of boat by implementing water Drag and Friction/Viscosity Force
  .luacheckrc
  mods/boats/init.lua
Labels: >= Two approvals, Feature

#2525 Add Russian translation
  mods/beds/locale/beds.ru.tr
  mods/binoculars/locale/binoculars.ru.tr
  mods/boats/locale/boats.ru.tr
  mods/bones/locale/bones.ru.tr
  mods/bucket/locale/bucket.ru.tr
  mods/bucket/textures/bucket.png
  mods/butterflies/locale/butterflies.ru.tr
  mods/carts/locale/carts.ru.tr
  mods/creative/locale/creative.ru.tr
  mods/default/locale/default.ru.tr
  mods/doors/locale/doors.ru.tr
  mods/dye/locale/dye.ru.tr
  mods/farming/locale/farming.ru.tr
  mods/fire/locale/fire.ru.tr
  mods/fireflies/locale/fireflies.ru.tr
  mods/flowers/locale/flowers.ru.tr
  mods/game_commands/locale/game_commands.ru.tr
  mods/map/locale/map.ru.tr
  mods/screwdriver/locale/screwdriver.ru.tr
  mods/sethome/locale/sethome.ru.tr
  mods/sfinv/locale/sfinv.ru.tr
  mods/stairs/locale/stairs.ru.tr
  mods/tnt/locale/tnt.ru.tr
  mods/vessels/locale/vessels.ru.tr
  mods/walls/locale/walls.ru.tr
  mods/wool/locale/wool.ru.tr
  mods/xpanes/locale/xpanes.ru.tr
Labels: One approval, Translation
