Repository luanti-org/minetest_game, pull requests merged in 2019-07, with the labels that each got.

#2400 Define dungeon nodes in biome definitions
  mods/default/mapgen.lua
Labels: Maintenance, Mapgen, Trivial

#2401 intersects_protection(): Fix compatibility code.
  mods/default/legacy.lua
Labels: Bugfix, One approval, Trivial

#2275 Sfinv creative tweaks
  mods/creative/inventory.lua
  mods/sfinv/api.lua
  mods/sfinv/init.lua
Labels: >= Two approvals

#2387 Open chests when wielding corals
  mods/default/nodes.lua
Labels: Bugfix, One approval

#2408 Removed stack_max from bucket:bucket_empty
  mods/bucket/init.lua
Labels: Maintenance, One approval, Trivial

#2406 New lighter, greyer permafrost texture
  mods/default/textures/default_permafrost.png
Labels: One approval, Textures

#2410 new_default_grass_texture2
  mods/default/README.txt
  mods/default/textures/default_grass.png
Labels: >= Two approvals, Textures

#2414 Switch to mod.conf, delete deprecated depends.txt
  mods/beds/depends.txt
  mods/beds/mod.conf
  mods/binoculars/depends.txt
  mods/binoculars/mod.conf
  mods/boats/depends.txt
  mods/boats/mod.conf
  mods/bones/depends.txt
  mods/bones/mod.conf
  mods/bucket/depends.txt
  mods/bucket/mod.conf
  mods/butterflies/depends.txt
  mods/butterflies/mod.conf
  mods/carts/depends.txt
  mods/carts/mod.conf
  mods/creative/depends.txt
  mods/creative/mod.conf
  mods/default/depends.txt
  mods/default/mod.conf
  mods/doors/depends.txt
  mods/doors/mod.conf
  mods/dungeon_loot/depends.txt
  mods/dungeon_loot/mod.conf
  mods/dye/depends.txt
  mods/dye/mod.conf
  mods/farming/depends.txt
  mods/farming/mod.conf
  mods/fire/depends.txt
  mods/fire/mod.conf
  mods/fireflies/depends.txt
  mods/fireflies/mod.conf
  mods/flowers/depends.txt
  mods/flowers/mod.conf
  mods/game_commands/mod.conf
  mods/give_initial_stuff/depends.txt
  mods/give_initial_stuff/mod.conf
  mods/map/depends.txt
  mods/map/mod.conf
  mods/player_api/mod.conf
  mods/screwdriver/mod.conf
  mods/sethome/mod.conf
  mods/sfinv/mod.conf
  mods/spawn/depends.txt
  mods/spawn/mod.conf
  mods/stairs/depends.txt
  mods/stairs/mod.conf
  mods/tnt/depends.txt
  mods/tnt/mod.conf
  mods/vessels/depends.txt
  mods/vessels/mod.conf
  mods/walls/depends.txt
  mods/walls/mod.conf
  mods/wool/depends.txt
  mods/wool/mod.conf
  mods/xpanes/depends.txt
  mods/xpanes/mod.conf
Labels: Maintenance, One approval

#2322 Enable colored Luacheck output on Travis CI
  .travis.yml
Labels: Maintenance

#2419 Creative: Remove unnecessary dependency on 'default'
  mods/creative/mod.conf
Labels: Maintenance, Trivial

#2411 Add new, longer 'default_grass_side' texture
  mods/default/README.txt
  mods/default/textures/default_grass_side.png
Labels: One approval, Textures

#2421 add default as optional dep for creative
  mods/creative/mod.conf
Labels: Bugfix, One approval, Trivial

#2422 add new dry dirt node
  mods/default/README.txt
  mods/default/functions.lua
  mods/default/mapgen.lua
  mods/default/nodes.lua
  mods/default/textures/default_dry_dirt.png
  mods/farming/nodes.lua
Labels: >= Two approvals, Feature, Mapgen, Textures

#2426 Add patches of bare 'dry dirt' to savanna
  mods/default/mapgen.lua
Labels: Feature, Mapgen, One approval

#2430 default:code cleanup
  mods/default/crafting.lua
  mods/default/nodes.lua
Labels: Maintenance, One approval, Trivial
