Repository luanti-org/minetest_game, pull requests merged in 2020-05, with the labels that each got.

#2662 doors: Remove unnecessary nodebox and empty texture
  mods/doors/init.lua
  mods/doors/textures/doors_blank.png
Labels: Maintenance, One approval

#2673 Add oddly_breakable_by_hand to glass stairs and slabs
  mods/stairs/init.lua
Labels: Bugfix, One approval

#2674 Switch TNT explosions to use add_player_velocity
  mods/tnt/init.lua
Labels: Feature, One approval, Trivial

#2670 doors: Update Italian translation
  mods/doors/locale/doors.it.tr
Labels: Translation, Trivial

#2680 Add new dry shrub texture by Extex101
  mods/default/README.txt
  mods/default/textures/default_dry_shrub.png
Labels: One approval, Textures

#2617 Add wild cotton plant in savanna as a source of cotton seeds
  mods/farming/README.txt
  mods/farming/init.lua
  mods/farming/license.txt
  mods/farming/nodes.lua
  mods/farming/textures/farming_cotton_wild.png
Labels: Feature, Mapgen, One approval

#2686 Add node particles when leafdecay removes a node
  mods/default/functions.lua
Labels: Feature, One approval

#2669 Reduce hud icons size to 12x12 pixels
  mods/default/README.txt
  mods/default/license.txt
  mods/default/textures/bubble.png
  mods/default/textures/heart.png
Labels: >= Two approvals, Textures

#2689 carts: Fix item collection
  mods/carts/cart_entity.lua
Labels: Bugfix, One approval, Trivial
