Repository luanti-org/minetest_game, pull requests merged in 2020-09, with the labels that each got.

#2730 Update Chinese translation
  mods/default/locale/default.zh_CN.tr
  mods/default/locale/default.zh_TW.tr
  mods/doors/locale/doors.zh_CN.tr
  mods/doors/locale/doors.zh_TW.tr
Labels: Maintenance, One approval, Translation

#2566 Fix beds
  mods/beds/functions.lua
Labels: >= Two approvals, Bugfix

#2737 Player_api: Various maintenance
  game_api.txt
  mods/player_api/api.lua
  mods/player_api/init.lua
Labels: Maintenance, One approval, Trivial

#2740 Update description to manage expectations
  game.conf
Labels: >= Two approvals, Documentation

#2741 Improve player model credits, add contributors to license
  mods/player_api/README.txt
  mods/player_api/license.txt
Labels: Documentation, Trivial

#2584 Inner/Outer Stairs translation in external mods
  game_api.txt
  mods/stairs/init.lua
Labels: >= Two approvals, Translation

#2328 Fix builtin item metatable.
  mods/default/item_entity.lua
Labels: >= Two approvals, Bugfix

#2639 furnace: Start the timer on on_metadata_inventory_take.
  mods/default/furnace.lua
Labels: >= Two approvals, Bugfix

#2718 Add icons for invisible nodes
  mods/butterflies/init.lua
  mods/default/nodes.lua
  mods/default/textures/default_invisible_node_overlay.png
  mods/doors/init.lua
  mods/doors/textures/doors_hidden_segment.png
  mods/fireflies/init.lua
  mods/tnt/init.lua
Labels: >= Two approvals, Maintenance, Textures
