Repository luanti-org/minetest_game, pull requests merged in 2020-06, with the labels that each got.

#2695 Use node particles for TNT explosions
  mods/tnt/init.lua
Labels: Feature, One approval

#2675 Implement searching for translated names in creative inventory
  mods/creative/inventory.lua
Labels: Feature, One approval

#2691 creative: Update for compatibility with minetest.creative_is_enabled
  game_api.txt
  mods/creative/init.lua
Labels: Maintenance, One approval

#2692 Change brake rail to red
  mods/carts/textures/carts_rail_crossing_brk.png
  mods/carts/textures/carts_rail_curved_brk.png
  mods/carts/textures/carts_rail_straight_brk.png
  mods/carts/textures/carts_rail_t_junction_brk.png
Labels: One approval, Textures

#2687 Make dry grass spread on default:dirt again
  mods/default/functions.lua
  mods/default/nodes.lua
Labels: Feature, One approval

#2705 Update nodes papyrus can grow on, include default:dry_dirt
  mods/default/functions.lua
Labels: Blocker, Bugfix, One approval

#2701 Update farming.es.tr
  mods/farming/locale/farming.es.tr
Labels: Translation, Trivial

#2711 Update German translation
  mods/default/locale/default.de.tr
  mods/farming/locale/farming.de.tr
  mods/fire/locale/fire.de.tr
Labels: >= Two approvals, Translation

#2685 TNT centre node adheres to protection
  mods/tnt/init.lua
Labels: Bugfix, One approval, Trivial

#2693 Add Indonesian translations
  mods/beds/locale/beds.id.tr
  mods/binoculars/locale/binoculars.id.tr
  mods/boats/locale/boats.id.tr
  mods/bones/locale/bones.id.tr
  mods/bucket/locale/bucket.id.tr
  mods/butterflies/locale/butterflies.id.tr
  mods/carts/locale/carts.id.tr
  mods/creative/locale/creative.id.tr
  mods/default/locale/default.id.tr
  mods/doors/locale/doors.id.tr
  mods/dye/locale/dye.id.tr
  mods/farming/locale/farming.id.tr
  mods/fire/locale/fire.id.tr
  mods/fireflies/locale/fireflies.id.tr
  mods/flowers/locale/flowers.id.tr
  mods/game_commands/locale/game_commands.id.tr
  mods/map/locale/map.id.tr
  mods/screwdriver/locale/screwdriver.id.tr
  mods/sethome/locale/sethome.id.tr
  mods/sfinv/locale/sfinv.id.tr
  mods/stairs/locale/stairs.id.tr
  mods/tnt/locale/tnt.id.tr
  mods/vessels/locale/vessels.id.tr
  mods/walls/locale/walls.id.tr
  mods/wool/locale/wool.id.tr
  mods/xpanes/locale/xpanes.id.tr
Labels: >= Two approvals, Translation
