Repository luanti-org/minetest_game, pull requests merged in 2020-12, with the labels that each got.

#2790 Don't replace protected liquids with bones.
  mods/bones/init.lua
Labels: Bugfix, One approval

#2758 Fixed some mistakes in the Indonesian translations
  mods/beds/locale/beds.id.tr
  mods/binoculars/locale/binoculars.id.tr
  mods/carts/locale/carts.id.tr
  mods/default/locale/default.id.tr
  mods/dye/locale/dye.id.tr
  mods/fire/locale/fire.id.tr
  mods/wool/locale/wool.id.tr
Labels: Translation

#2796 Update zh_CN translation for mtg_craftguide and dye
  mods/dye/locale/dye.zh_CN.tr
  mods/dye/locale/dye.zh_TW.tr
  mods/mtg_craftguide/locale/mtg_craftguide.zh_CN.tr
  mods/mtg_craftguide/locale/mtg_craftguide.zh_TW.tr
Labels: Translation

#2794 Improve Russian translation (carts)
  mods/carts/locale/carts.ru.tr
Labels: One approval, Translation

#2795 Use Minetest 5.3 'minetest.is_creative_enabled' API
  mods/beds/api.lua
  mods/binoculars/init.lua
  mods/binoculars/mod.conf
  mods/boats/init.lua
  mods/bones/init.lua
  mods/carts/cart_entity.lua
  mods/creative/init.lua
  mods/creative/inventory.lua
  mods/default/nodes.lua
  mods/default/trees.lua
  mods/doors/init.lua
  mods/farming/api.lua
  mods/fire/init.lua
  mods/fireflies/init.lua
  mods/flowers/init.lua
  mods/map/init.lua
  mods/map/mod.conf
  mods/screwdriver/init.lua
  mods/stairs/init.lua
Labels: >= Two approvals, Maintenance

#2788 Fix boat floating in the air when water being drained away (#2778)
  mods/boats/init.lua
Labels: >= Two approvals, Bugfix, Feature
