Repository luanti-org/minetest_game, pull requests merged in 2020-02, with the labels that each got.

#2583 Convert minetest.sound_play uses to ephemeral
  mods/carts/cart_entity.lua
  mods/default/chests.lua
  mods/default/functions.lua
  mods/default/item_entity.lua
  mods/default/torch.lua
  mods/doors/init.lua
  mods/farming/api.lua
  mods/fire/init.lua
  mods/tnt/init.lua
Labels: Maintenance, One approval, Sounds

#2579 Add traditional Chinese translation(default)
  mods/default/locale/default.zh_TW.tr
Labels: >= Two approvals, Translation

#2588 Fix simple bed height, make player lay down just above it, not inside it
  mods/beds/beds.lua
  mods/beds/functions.lua
Labels: Bugfix, Trivial

#2591 Fix french translation of snow block slab
  mods/stairs/locale/stairs.fr.tr
Labels: Bugfix, Translation, Trivial

#2580 Fix missing papyrus in savanna, add a dry dirt version
  mods/default/mapgen.lua
  mods/default/schematics/papyrus_on_dirt.mts
  mods/default/schematics/papyrus_on_dry_dirt.mts
  schematic_tables.txt
Labels: Bugfix, High priority, Mapgen, Trivial

#2565 Add log for seeds on place
  mods/farming/api.lua
Labels: Feature, One approval, Trivial

#2595 Fix invalid rotations by torches
  mods/default/torch.lua
Labels: Bugfix, One approval, Trivial

#2573 [REDO] Accelerate water/river water animations.
  mods/default/nodes.lua
Labels: One approval, Trivial

#2602 Sort loot registration into respective mods
  mods/bucket/init.lua
  mods/bucket/mod.conf
  mods/carts/init.lua
  mods/carts/mod.conf
  mods/dungeon_loot/loot.lua
  mods/farming/init.lua
  mods/farming/mod.conf
  mods/vessels/init.lua
  mods/vessels/mod.conf
Labels: >= Two approvals, Maintenance
