Repository luanti-org/minetest_game, pull requests merged in 2020-04, with the labels that each got.

#2631 Fix respawn not working at all when suitable position was not found
  mods/spawn/init.lua
Labels: Bugfix, One approval

#2612 Sort items into correct categories
  game_api.txt
  mods/creative/inventory.lua
  mods/doors/init.lua
  mods/xpanes/init.lua
Labels: >= Two approvals, Feature

#2607 Transform brick top texture to align bricks correctly
  mods/default/nodes.lua
Labels: >= Two approvals, Textures

#2622 Enable animation when Right Click
  mods/player_api/api.lua
Labels: >= Two approvals, Feature, Models

#2628 Clarify descriptions of dry grass, dry dirt
  mods/default/nodes.lua
  mods/farming/nodes.lua
Labels: Maintenance, One approval

#2633 Weather mod: Tune cloud density variation
  mods/weather/init.lua
Labels: Bugfix, Maintenance, One approval

#2637 trees: Reduce local variables.
  mods/default/trees.lua
Labels: Maintenance, Trivial

#2636 Fix crash on TNT explosions if tnt is disabled
  mods/tnt/init.lua
Labels: Bugfix, Trivial

#2635 Fix creative category sorting in certain cases
  mods/creative/inventory.lua
Labels: Bugfix, Trivial

#2640 player_api: Remove local variable.
  mods/player_api/api.lua
Labels: Maintenance, One approval

#2568 Add Basic Fire Description
  mods/fire/init.lua
  mods/fire/locale/fire.zh_CN.tr
  mods/fire/locale/fire.zh_TW.tr
Labels: Maintenance, One approval, Translation

#2627 Make straw stairs usable as fuel
  mods/farming/init.lua
  mods/farming/nodes.lua
Labels: >= Two approvals, Bugfix

#2127 Make default.chest.register_chest() usable for other mods
  game_api.txt
  mods/default/chests.lua
Labels: >= Two approvals, Bugfix

#2647 Make default:snow collisionbox half of nodebox height
  mods/default/nodes.lua
Labels: One approval, Trivial

#2654 Use Player API functions
  mods/beds/functions.lua
Labels: Maintenance, One approval

#2659 Fix flammable item entities crashing
  mods/default/item_entity.lua
Labels: Bugfix, High priority, One approval

#2651 Small sign changes
  mods/default/nodes.lua
Labels: Maintenance, Trivial

#2666 Cart inventory image was rendering the side twice
  mods/carts/cart_entity.lua
Labels: Bugfix, Trivial
