Repository luanti-org/minetest_game, pull requests merged in 2020-11, with the labels that each got.

#2770 Fix deprecated get_player_velocity and set_physics_override calls
  mods/beds/functions.lua
  mods/tnt/init.lua
Labels: Bugfix, One approval, Trivial

#2772 Slovak translations
  mods/beds/locale/beds.sk.tr
  mods/binoculars/locale/binoculars.sk.tr
  mods/boats/locale/boats.sk.tr
  mods/bones/locale/bones.sk.tr
  mods/bucket/locale/bucket.sk.tr
  mods/butterflies/locale/butterflies.sk.tr
  mods/carts/locale/carts.sk.tr
  mods/creative/locale/creative.sk.tr
  mods/default/locale/default.sk.tr
  mods/doors/locale/doors.sk.tr
  mods/dye/locale/dye.sk.tr
  mods/farming/locale/farming.sk.tr
  mods/fire/locale/fire.sk.tr
  mods/fireflies/locale/fireflies.sk.tr
  mods/flowers/locale/flowers.sk.tr
  mods/game_commands/locale/game_commands.sk.tr
  mods/map/locale/map.sk.tr
  mods/screwdriver/locale/screwdriver.sk.tr
  mods/sethome/locale/sethome.sk.tr
  mods/sfinv/locale/sfinv.sk.tr
  mods/stairs/locale/stairs.sk.tr
  mods/tnt/locale/tnt.sk.tr
  mods/vessels/locale/vessels.sk.tr
  mods/walls/locale/walls.sk.tr
  mods/wool/locale/wool.sk.tr
  mods/xpanes/locale/xpanes.sk.tr
Labels: Translation

#2761 more accurate russian translation.
  mods/default/locale/default.ru.tr
  mods/fire/locale/fire.ru.tr
  mods/wool/locale/wool.ru.tr
Labels: One approval, Translation

#2764 Add missing not_in_creative_inventory group where appropriate
  mods/beds/api.lua
  mods/default/tools.lua
  mods/tnt/init.lua
Labels: >= Two approvals, Bugfix, Maintenance

#2746 Move player sitting and laying position to above the ground
  mods/player_api/models/character.b3d
  mods/player_api/models/character.blend
Labels: >= Two approvals, Bugfix, Concept approved, Models

#2785 Fix minor bug in german translation. Fixes #2784
  mods/default/locale/default.de.tr
  mods/stairs/locale/stairs.de.tr
  mods/walls/locale/walls.de.tr
Labels: One approval, Translation
