Repository luanti-org/minetest_game, pull requests merged in 2020-01, with the labels that each got.

#2553 Sort recipes into corresponding files
  mods/default/chests.lua
  mods/default/crafting.lua
  mods/default/craftitems.lua
  mods/default/furnace.lua
  mods/default/tools.lua
  mods/default/torch.lua
Labels: >= Two approvals, Maintenance

#2363 Move duplicate recipe from books to default.register_duplicate_recipe()
  game_api.txt
  mods/default/craftitems.lua
  mods/default/functions.lua
Labels: Feature, Maintenance, One approval, Trivial

#2290 can_interact_with_node check for group key
  mods/default/craftitems.lua
  mods/default/functions.lua
Labels: >= Two approvals, Feature

#2556 Change name of "Pickaxe" in Russian translation
  mods/default/locale/default.ru.tr
Labels: One approval, Translation, Trivial

#2561 Add zh_CN translation
  mods/beds/locale/beds.zh_CN.tr
  mods/binoculars/locale/binoculars.zh_CN.tr
  mods/boats/locale/boats.zh_CN.tr
  mods/bones/locale/bones.zh_CN.tr
  mods/bucket/locale/bucket.zh_CN.tr
  mods/butterflies/locale/butterflies.zh_CN.tr
  mods/carts/locale/carts.zh_CN.tr
  mods/creative/locale/creative.zh_CN.tr
  mods/default/locale/default.zh_CN.tr
  mods/doors/locale/doors.zh_CN.tr
  mods/dye/locale/dye.zh_CN.tr
  mods/farming/locale/farming.zh_CN.tr
  mods/fire/locale/fire.zh_CN.tr
  mods/fireflies/locale/fireflies.zh_CN.tr
  mods/flowers/locale/flowers.zh_CN.tr
  mods/game_commands/locale/game_commands.zh_CN.tr
  mods/map/locale/map.zh_CN.tr
  mods/screwdriver/locale/screwdriver.zh_CN.tr
  mods/sethome/locale/sethome.zh_CN.tr
  mods/sfinv/locale/sfinv.zh_CN.tr
  mods/stairs/locale/stairs.zh_CN.tr
  mods/tnt/locale/tnt.zh_CN.tr
  mods/vessels/locale/vessels.zh_CN.tr
  mods/walls/locale/walls.zh_CN.tr
  mods/wool/locale/wool.zh_CN.tr
  mods/xpanes/locale/xpanes.zh_CN.tr
Labels: One approval, Translation

#2563 Update Chinese translation
  mods/default/locale/default.zh_CN.tr
Labels: One approval, Translation

#2357 Reset spawn position on bed destruction
  mods/beds/api.lua
  mods/beds/spawns.lua
Labels: >= Two approvals, Bugfix
