Repository luanti-org/minetest_game, pull requests merged in 2020-03, with the labels that each got.

#2611 Creative: Skip redundant refreshes, fix reset button
  mods/creative/inventory.lua
Labels: Bugfix, One approval

#2613 Dungeon loot: Warn on unknown registered loot items
  mods/dungeon_loot/mapgen.lua
Labels: Maintenance, One approval, Trivial

#2616 Fix TNT mod crash when entities disappear during explosion
  mods/tnt/init.lua
Labels: Bugfix, One approval

#2614 xpanes:remove unused textures
  mods/xpanes/init.lua
  mods/xpanes/textures/xpanes_bar_top.png
  mods/xpanes/textures/xpanes_pane_half.png
  mods/xpanes/textures/xpanes_space.png
Labels: Maintenance, One approval

#2618 xpanes: Fix code style
  mods/xpanes/init.lua
Labels: Maintenance, Trivial

#2620 player_api: Prevent knockback when player is set as attached
  .luacheckrc
  game_api.txt
  mods/player_api/api.lua
Labels: Bugfix, One approval
