Repository luanti-org/minetest_game, pull requests merged in 2021-02, with the labels that each got.

#2789 Beds: Preserve player physics
  mods/beds/functions.lua
Labels: Bugfix, Feature, One approval

#2820 Smoothen lava sounds at loop points
  mods/env_sounds/sounds/env_sounds_lava.1.ogg
  mods/env_sounds/sounds/env_sounds_lava.2.ogg
Labels: >= Two approvals, Bugfix, Sounds

#2821 Update German translation
  mods/beds/locale/beds.de.tr
  mods/default/locale/default.de.tr
  mods/mtg_craftguide/locale/mtg_craftguide.de.tr
Labels: >= Two approvals, Translation

#2824 Update Spanish translation
  mods/beds/locale/beds.es.tr
  mods/default/locale/default.es.tr
  mods/fire/locale/fire.es.tr
  mods/mtg_craftguide/locale/mtg_craftguide.es.tr
Labels: One approval, Translation

#2834 l10n/pt_BR: added Brazilian Portuguese translation
  mods/beds/locale/beds.pt_BR.tr
  mods/binoculars/locale/binoculars.pt_BR.tr
  mods/boats/locale/boats.pt_BR.tr
  mods/bones/locale/bones.pt_BR.tr
  mods/bucket/locale/bucket.pt_BR.tr
  mods/butterflies/locale/butterflies.pt_BR.tr
  mods/carts/locale/carts.pt_BR.tr
  mods/creative/locale/creative.pt_BR.tr
  mods/default/locale/default.pt_BR.tr
  mods/doors/locale/doors.pt_BR.tr
  mods/dye/locale/dye.pt_BR.tr
  mods/farming/locale/farming.pt_BR.tr
  mods/fire/locale/fire.pt_BR.tr
  mods/fireflies/locale/fireflies.pt_BR.tr
  mods/flowers/locale/flowers.pt_BR.tr
  mods/game_commands/locale/game_commands.pt_BR.tr
  mods/map/locale/map.pt_BR.tr
  mods/mtg_craftguide/locale/mtg_craftguide.pt_BR.tr
  mods/screwdriver/locale/screwdriver.pt_BR.tr
  mods/sethome/locale/sethome.pt_BR.tr
  mods/sfinv/locale/sfinv.pt_BR.tr
  mods/stairs/locale/stairs.pt_BR.tr
  mods/tnt/locale/tnt.pt_BR.tr
  mods/vessels/locale/vessels.pt_BR.tr
  mods/walls/locale/walls.pt_BR.tr
  mods/wool/locale/wool.pt_BR.tr
  mods/xpanes/locale/xpanes.pt_BR.tr
Labels: Translation

#2835 Add Lojban translation
  mods/beds/locale/beds.jbo.tr
  mods/binoculars/locale/binoculars.jbo.tr
  mods/boats/locale/boats.jbo.tr
  mods/bones/locale/bones.jbo.tr
  mods/bucket/locale/bucket.jbo.tr
  mods/butterflies/locale/butterflies.jbo.tr
  mods/carts/locale/carts.jbo.tr
  mods/creative/locale/creative.jbo.tr
  mods/default/locale/default.jbo.tr
  mods/doors/locale/doors.jbo.tr
  mods/dye/locale/dye.jbo.tr
  mods/farming/locale/farming.jbo.tr
  mods/fire/locale/fire.jbo.tr
  mods/fireflies/locale/fireflies.jbo.tr
  mods/flowers/locale/flowers.jbo.tr
  mods/game_commands/locale/game_commands.jbo.tr
  mods/map/locale/map.jbo.tr
  mods/mtg_craftguide/locale/mtg_craftguide.jbo.tr
  mods/screwdriver/locale/screwdriver.jbo.tr
  mods/sethome/locale/sethome.jbo.tr
  mods/sfinv/locale/sfinv.jbo.tr
  mods/stairs/locale/stairs.jbo.tr
  mods/tnt/locale/tnt.jbo.tr
  mods/vessels/locale/vessels.jbo.tr
  mods/walls/locale/walls.jbo.tr
  mods/wool/locale/wool.jbo.tr
  mods/xpanes/locale/xpanes.jbo.tr
Labels: Translation
