Repository luanti-org/minetest_game, pull requests merged in 2021-05, with the labels that each got.

#2862 Check for attachments before attaching player to bed
  mods/beds/functions.lua
Labels: Bugfix, One approval, Trivial

#2851 Reclassify some items
  mods/binoculars/init.lua
  mods/map/init.lua
Labels: Bugfix, One approval, Trivial

#2863 Use group for mushroom spread ABM
  mods/flowers/init.lua
Labels: Feature, One approval, Trivial

#2768 Add optional open/close sound gain fields to the Doors API. Balance sound levels
  game_api.txt
  mods/doors/init.lua
  mods/xpanes/init.lua
Labels: Feature, Maintenance, One approval, Sounds
