Repository luanti-org/minetest_game, pull requests merged in 2021-12, with the labels that each got.

#2906 Convert door model to B3D
  mods/doors/init.lua
  mods/doors/models/door.blend
  mods/doors/models/door_a.b3d
  mods/doors/models/door_a.obj
  mods/doors/models/door_a2.obj
  mods/doors/models/door_b.b3d
  mods/doors/models/door_b.obj
  mods/doors/models/door_b2.obj
Labels: >= Two approvals, Bugfix, Maintenance

#2905 Slovak translation update
  mods/beds/locale/beds.sk.tr
  mods/boats/locale/boats.sk.tr
Labels: One approval, Translation

#2911 Pull some parent node vars for stairs and slabs
  game_api.txt
  mods/stairs/init.lua
Labels: >= Two approvals, Bugfix
