Repository luanti-org/minetest_game, pull requests merged in 2021-01, with the labels that each got.

#2806 Do not crash when a skeleton key is used on an unknown node
  mods/default/craftitems.lua
Labels: Bugfix, Trivial

#2799 Add missing nodes to list
  mods/default/nodes.lua
Labels: Documentation, One approval, Trivial

#2800 Correct name of acacia mese postlight
  mods/default/nodes.lua
Labels: Blocker, Bugfix, Maintenance, One approval

#2804 Correct door model dimensions
  mods/doors/models/door_a.obj
  mods/doors/models/door_a2.obj
  mods/doors/models/door_b.obj
  mods/doors/models/door_b2.obj
Labels: Maintenance, Models, One approval
