Repository luanti-org/minetest_game, pull requests merged in 2022-02, with the labels that each got.

#2925 Refinement translation for UK and RU langs (Drinking Glass)
  mods/vessels/locale/vessels.ru.tr
  mods/vessels/locale/vessels.uk.tr
Labels: Translation

#2928 player_api - fix compatibility code
  mods/player_api/api.lua
Labels: Trivial, Bugfix

#2931 Refinement translation for UK and RU langs (Cotton)
  mods/farming/locale/farming.ru.tr
  mods/farming/locale/farming.uk.tr
Labels: One approval, Bugfix, Translation
