Repository luanti-org/minetest_game, pull requests merged in 2022-05, with the labels that each got.

#2941 Deduplicate player action logging, silence fake player actions
  game_api.txt
  minetest.conf.example
  mods/default/chests.lua
  mods/default/functions.lua
  mods/default/nodes.lua
  mods/default/trees.lua
  mods/farming/api.lua
  mods/tnt/init.lua
  mods/vessels/init.lua
  settingtypes.txt
Labels: >= Two approvals, Feature, Maintenance

#2951 Carts: Improve movement behaviour
  mods/carts/cart_entity.lua
Labels: One approval, Maintenance

#2926 Polish translation
  mods/beds/locale/beds.pl.tr
  mods/binoculars/locale/binoculars.pl.tr
  mods/boats/locale/boats.pl.tr
  mods/bones/locale/bones.pl.tr
  mods/bucket/locale/bucket.pl.tr
  mods/butterflies/locale/butterflies.pl.tr
  mods/carts/locale/carts.pl.tr
  mods/creative/locale/creative.pl.tr
  mods/default/locale/default.pl.tr
  mods/doors/locale/doors.pl.tr
  mods/dye/locale/dye.pl.tr
  mods/farming/locale/farming.pl.tr
  mods/fire/locale/fire.pl.tr
  mods/fireflies/locale/fireflies.pl.tr
  mods/flowers/locale/flowers.pl.tr
  mods/game_commands/locale/game_commands.pl.tr
  mods/keys/locale/keys.pl.tr
  mods/map/locale/map.pl.tr
  mods/mtg_craftguide/locale/mtg_craftguide.pl.tr
  mods/screwdriver/locale/screwdriver.pl.tr
  mods/sethome/locale/sethome.pl.tr
  mods/sfinv/locale/sfinv.pl.tr
  mods/stairs/locale/stairs.pl.tr
  mods/tnt/locale/tnt.pl.tr
  mods/vessels/locale/vessels.pl.tr
  mods/walls/locale/walls.pl.tr
  mods/wool/locale/wool.pl.tr
  mods/xpanes/locale/xpanes.pl.tr
Labels: >= Two approvals, Translation

#2955 Fix furnace fire sound stopping too late
  mods/default/furnace.lua
Labels: >= Two approvals, Bugfix, Concept approved
