Repository luanti-org/minetest_game, pull requests merged in 2022-01, with the labels that each got.

#2871 Allow to set use_texture_alpha when registering a door
  game_api.txt
  mods/doors/init.lua
Labels: One approval, Feature

#2745 Redo player_api
  game_api.txt
  mods/beds/functions.lua
  mods/player_api/api.lua
  mods/player_api/init.lua
  mods/player_api/mod.conf
Labels: One approval, Bugfix, Feature, Maintenance

#2917 Override local_animation settings for certain animations
  game_api.txt
  mods/player_api/api.lua
  mods/player_api/init.lua
Labels: One approval, Feature

#2919 Copyediting `README.md`
  README.md
  game.conf
Labels: >= Two approvals

#2774 Balance sounds, remove silent water footstep
  mods/default/README.txt
  mods/default/functions.lua
  mods/default/furnace.lua
  mods/default/item_entity.lua
  mods/default/sounds/default_water_footstep.4.ogg
  mods/default/torch.lua
  mods/farming/api.lua
  mods/fire/init.lua
  mods/tnt/init.lua
Labels: >= Two approvals, Sounds, Maintenance

#2922 Update french translations
  mods/beds/locale/beds.fr.tr
  mods/default/locale/default.fr.tr
  mods/farming/locale/farming.fr.tr
  mods/fire/locale/fire.fr.tr
  mods/mtg_craftguide/locale/mtg_craftguide.fr.tr
Labels: >= Two approvals, Translation

#2920 Fix and update Swedish translation.
  mods/beds/locale/beds.se.tr
  mods/beds/locale/beds.sv.tr
  mods/binoculars/locale/binoculars.se.tr
  mods/binoculars/locale/binoculars.sv.tr
  mods/boats/locale/boats.sv.tr
  mods/bones/locale/bones.sv.tr
  mods/bucket/locale/bucket.se.tr
  mods/bucket/locale/bucket.sv.tr
  mods/butterflies/locale/butterflies.sv.tr
  mods/carts/locale/carts.sv.tr
  mods/creative/locale/creative.se.tr
  mods/creative/locale/creative.sv.tr
  mods/default/locale/default.se.tr
  mods/default/locale/default.sv.tr
  mods/doors/locale/doors.se.tr
  mods/doors/locale/doors.sv.tr
  mods/dye/locale/dye.se.tr
  mods/dye/locale/dye.sv.tr
  mods/farming/locale/farming.se.tr
  mods/farming/locale/farming.sv.tr
  mods/fire/locale/fire.se.tr
  mods/fire/locale/fire.sv.tr
  mods/fireflies/locale/fireflies.sv.tr
  mods/flowers/locale/flowers.se.tr
  mods/flowers/locale/flowers.sv.tr
  mods/game_commands/locale/game_commands.sv.tr
  mods/keys/locale/keys.sv.tr
  mods/map/locale/map.se.tr
  mods/map/locale/map.sv.tr
  mods/mtg_craftguide/locale/mtg_craftguide.sv.tr
  mods/screwdriver/locale/screwdriver.sv.tr
  mods/sethome/locale/sethome.sv.tr
  mods/sfinv/locale/sfinv.sv.tr
  mods/stairs/locale/stairs.se.tr
  mods/stairs/locale/stairs.sv.tr
  mods/tnt/locale/tnt.sv.tr
  mods/vessels/locale/vessels.se.tr
  mods/vessels/locale/vessels.sv.tr
  mods/walls/locale/walls.se.tr
  mods/walls/locale/walls.sv.tr
  mods/wool/locale/wool.se.tr
  mods/wool/locale/wool.sv.tr
  mods/xpanes/locale/xpanes.se.tr
  mods/xpanes/locale/xpanes.sv.tr
Labels: >= Two approvals, Translation

#2921 Add ukrainian (uk) translation
  mods/beds/locale/beds.uk.tr
  mods/binoculars/locale/binoculars.uk.tr
  mods/boats/locale/boats.uk.tr
  mods/bones/locale/bones.uk.tr
  mods/bucket/locale/bucket.uk.tr
  mods/butterflies/locale/butterflies.uk.tr
  mods/carts/locale/carts.uk.tr
  mods/creative/locale/creative.uk.tr
  mods/default/locale/default.uk.tr
  mods/doors/locale/doors.uk.tr
  mods/dye/locale/dye.uk.tr
  mods/farming/locale/farming.uk.tr
  mods/fire/locale/fire.uk.tr
  mods/fireflies/locale/fireflies.uk.tr
  mods/flowers/locale/flowers.uk.tr
  mods/game_commands/locale/game_commands.uk.tr
  mods/keys/locale/keys.uk.tr
  mods/map/locale/map.uk.tr
  mods/mtg_craftguide/locale/mtg_craftguide.uk.tr
  mods/screwdriver/locale/screwdriver.uk.tr
  mods/sethome/locale/sethome.uk.tr
  mods/sfinv/locale/sfinv.uk.tr
  mods/stairs/locale/stairs.uk.tr
  mods/tnt/locale/tnt.uk.tr
  mods/vessels/locale/vessels.uk.tr
  mods/walls/locale/walls.uk.tr
  mods/wool/locale/wool.uk.tr
  mods/xpanes/locale/xpanes.uk.tr
Labels: >= Two approvals, Translation

#2371 Add trapdoor/door model specification
  game_api.txt
  mods/doors/init.lua
Labels: >= Two approvals, Feature

#2924 Update Ukranian (uk) translation
  mods/bones/locale/bones.uk.tr
  mods/default/locale/default.uk.tr
  mods/stairs/locale/stairs.uk.tr
Labels: Translation
