Repository luanti-org/minetest_game, pull requests merged in 2022-07, with the labels that each got.

#2963 remove paramtype2="glasslikeliquidlevel" from glass nodes
  mods/default/nodes.lua
Labels: One approval, Trivial, Maintenance

#2923 Update Lojban translation (also fixes wrong language in sethome)
  mods/default/locale/default.jbo.tr
  mods/doors/locale/doors.jbo.tr
  mods/farming/locale/farming.jbo.tr
  mods/flowers/locale/flowers.jbo.tr
  mods/sethome/locale/sethome.jbo.tr
  mods/stairs/locale/stairs.jbo.tr
Labels: >= Two approvals, Obscure, Translation

#2910 Correct some Esperanto translations
  mods/beds/locale/beds.eo.tr
  mods/binoculars/locale/binoculars.eo.tr
  mods/bones/locale/bones.eo.tr
  mods/butterflies/locale/butterflies.eo.tr
  mods/carts/locale/carts.eo.tr
  mods/creative/locale/creative.eo.tr
  mods/default/locale/default.eo.tr
  mods/doors/locale/doors.eo.tr
  mods/dye/locale/dye.eo.tr
  mods/farming/locale/farming.eo.tr
  mods/fireflies/locale/fireflies.eo.tr
  mods/flowers/locale/flowers.eo.tr
  mods/game_commands/locale/game_commands.eo.tr
  mods/map/locale/map.eo.tr
  mods/mtg_craftguide/locale/mtg_craftguide.eo.tr
  mods/screwdriver/locale/screwdriver.eo.tr
  mods/sethome/locale/sethome.eo.tr
  mods/stairs/locale/stairs.eo.tr
  mods/vessels/locale/vessels.eo.tr
  mods/wool/locale/wool.eo.tr
  mods/xpanes/locale/xpanes.eo.tr
Labels: >= Two approvals, Translation

#2873 Adding Russian translation for mtg_craftguide
  mods/mtg_craftguide/locale/mtg_craftguide.ru.tr
Labels: One approval, Translation

#2973 Update Russian translation
  mods/default/locale/default.ru.tr
Labels: One approval, Trivial, Translation
