Repository luanti-org/minetest_game, pull requests merged in 2023-01, with the labels that each got.

#3007 Update Japanese translation
  mods/bucket/locale/bucket.ja.tr
  mods/default/locale/default.ja.tr
  mods/doors/locale/doors.ja.tr
  mods/farming/locale/farming.ja.tr
  mods/stairs/locale/stairs.ja.tr
  mods/walls/locale/walls.ja.tr
Labels: One approval, Translation

#3008 Update Chinese Translation
  mods/beds/locale/beds.zh_TW.tr
  mods/default/locale/default.zh_CN.tr
  mods/default/locale/default.zh_TW.tr
  mods/farming/locale/farming.zh_TW.tr
  mods/sethome/locale/sethome.zh_CN.tr
  mods/sethome/locale/sethome.zh_TW.tr
  mods/sethome/locale/template.txt
Labels: One approval, Translation

#2984 creative: Override Hand After Mods Loaded
  mods/creative/init.lua
  mods/creative/mod.conf
Labels: >= Two approvals, Maintenance

#3009 Flip item textures of glass doors
  mods/doors/textures/doors_item_glass.png
  mods/doors/textures/doors_item_obsidian_glass.png
Labels: Textures, >= Two approvals

#3012 Fix `player_api.set_model` not updating the animation
  mods/player_api/api.lua
Labels: One approval, Bugfix
