Repository luanti-org/minetest_game, pull requests merged in 2023-12, with the labels that each got.

#3078 Update Malay translations
  mods/beds/locale/beds.ms.tr
  mods/boats/locale/boats.ms.tr
  mods/creative/locale/creative.ms.tr
  mods/default/locale/default.ms.tr
  mods/dye/locale/dye.ms.tr
  mods/farming/locale/farming.ms.tr
  mods/fire/locale/fire.ms.tr
  mods/game_commands/locale/game_commands.ms.tr
  mods/mtg_craftguide/locale/mtg_craftguide.ms.tr
  mods/sethome/locale/sethome.ms.tr
  mods/tnt/locale/tnt.ms.tr
  mods/vessels/locale/vessels.ms.tr
  mods/wool/locale/wool.ms.tr
Labels: Translation

#2947 Mapgen: Don't clear biomes, decorations and ores
  mods/default/mapgen.lua
Labels: One approval, Bugfix, Maintenance

#3082 Update README.md for 5.8
  README.md
Labels: One approval

#2976 Bed bug fix: Remove "reverse" toggle in favor of swap_node/set_node combo
  mods/beds/api.lua
Labels: >= Two approvals, Bugfix

#3081 Use a faster and newer LuaCheck
  .github/workflows/build.yml
  .github/workflows/luacheck.yml
Labels: One approval, Maintenance

#3088 Make cloud parameters deterministic across sessions
  mods/weather/init.lua
Labels: Bugfix

#3058 Update Russian translation
  mods/beds/locale/beds.ru.tr
  mods/binoculars/locale/binoculars.ru.tr
  mods/bones/locale/bones.ru.tr
  mods/bucket/locale/bucket.ru.tr
  mods/butterflies/locale/butterflies.ru.tr
  mods/carts/locale/carts.ru.tr
  mods/creative/locale/creative.ru.tr
  mods/default/locale/default.ru.tr
  mods/doors/locale/doors.ru.tr
  mods/dye/locale/dye.ru.tr
  mods/farming/locale/farming.ru.tr
  mods/fire/locale/fire.ru.tr
  mods/fireflies/locale/fireflies.ru.tr
  mods/flowers/locale/flowers.ru.tr
  mods/game_commands/locale/game_commands.ru.tr
  mods/keys/locale/keys.ru.tr
  mods/map/locale/map.ru.tr
  mods/mtg_craftguide/locale/mtg_craftguide.ru.tr
  mods/screwdriver/locale/screwdriver.ru.tr
  mods/sethome/locale/sethome.ru.tr
  mods/stairs/locale/stairs.ru.tr
  mods/tnt/locale/tnt.ru.tr
  mods/vessels/locale/vessels.ru.tr
  mods/walls/locale/walls.ru.tr
  mods/wool/locale/wool.ru.tr
  mods/xpanes/locale/xpanes.ru.tr
Labels: One approval, Translation
