Repository luanti-org/minetest_game, pull requests merged in 2023-11, with the labels that each got.

#3073 Fix not updating vessel shelf infotext
  mods/vessels/init.lua
Labels: One approval, Bugfix

#3070 "Fix" of Ukrainian localisation
  mods/beds/locale/beds.uk.tr
  mods/binoculars/locale/binoculars.uk.tr
  mods/bones/locale/bones.uk.tr
  mods/bucket/locale/bucket.uk.tr
  mods/butterflies/locale/butterflies.uk.tr
  mods/carts/locale/carts.uk.tr
  mods/creative/locale/creative.uk.tr
  mods/default/locale/default.uk.tr
  mods/doors/locale/doors.uk.tr
  mods/dye/locale/dye.uk.tr
  mods/farming/locale/farming.uk.tr
  mods/fire/locale/fire.uk.tr
  mods/fireflies/locale/fireflies.uk.tr
  mods/flowers/locale/flowers.uk.tr
  mods/game_commands/locale/game_commands.uk.tr
  mods/keys/locale/keys.uk.tr
  mods/map/locale/map.uk.tr
  mods/mtg_craftguide/locale/mtg_craftguide.uk.tr
  mods/screwdriver/locale/screwdriver.uk.tr
  mods/sethome/locale/sethome.uk.tr
  mods/sfinv/locale/sfinv.uk.tr
  mods/stairs/locale/stairs.uk.tr
  mods/tnt/locale/tnt.uk.tr
  mods/vessels/locale/vessels.uk.tr
  mods/walls/locale/walls.uk.tr
  mods/wool/locale/wool.uk.tr
  mods/xpanes/locale/xpanes.uk.tr
Labels: One approval, Translation

#3077 Update Indonesian translations
  mods/binoculars/locale/binoculars.id.tr
  mods/creative/locale/creative.id.tr
  mods/game_commands/locale/game_commands.id.tr
  mods/map/locale/map.id.tr
  mods/mtg_craftguide/locale/mtg_craftguide.id.tr
  mods/sethome/locale/sethome.id.tr
Labels: Translation
