Repository luanti-org/minetest_game, pull requests merged in 2023-09, with the labels that each got.

#3059 Update creative Spanish translation
  mods/creative/locale/creative.es.tr
Labels: One approval, Trivial, Translation

#3060 Stairs: Add helper function for textures
  mods/stairs/init.lua
Labels: One approval, Maintenance

#3053 Better sapling grow system
  .luacheckrc
  game_api.txt
  mods/default/trees.lua
Labels: >= Two approvals, Maintenance

#3062 Fix corals and kelps duping with mesecons' sticky piston
  mods/default/nodes.lua
Labels: >= Two approvals, Bugfix

#3067 Fix bed night skip race condition
  mods/beds/functions.lua
Labels: Bugfix
