Repository luanti-org/minetest_game, pull requests merged in 2024-01, with the labels that each got.

#3089 Fix some placer nil checks
  mods/butterflies/init.lua
  mods/carts/cart_entity.lua
  mods/default/nodes.lua
  mods/default/trees.lua
  mods/farming/api.lua
  mods/tnt/init.lua
Labels: Bugfix

#3097 Allow overriding the loop flag on `player_api.set_animation`
  mods/player_api/api.lua
Labels: Maintenance, Supported by core dev

#3092 Tweak capitalization in Esperanto translation
  mods/beds/locale/beds.eo.tr
  mods/bucket/locale/bucket.eo.tr
  mods/butterflies/locale/butterflies.eo.tr
  mods/carts/locale/carts.eo.tr
  mods/default/locale/default.eo.tr
  mods/doors/locale/doors.eo.tr
  mods/dye/locale/dye.eo.tr
  mods/farming/locale/farming.eo.tr
  mods/fire/locale/fire.eo.tr
  mods/fireflies/locale/fireflies.eo.tr
  mods/flowers/locale/flowers.eo.tr
  mods/keys/locale/keys.eo.tr
  mods/map/locale/map.eo.tr
  mods/mtg_craftguide/locale/mtg_craftguide.eo.tr
  mods/stairs/locale/stairs.eo.tr
  mods/tnt/locale/tnt.eo.tr
  mods/vessels/locale/vessels.eo.tr
  mods/walls/locale/walls.eo.tr
  mods/wool/locale/wool.eo.tr
  mods/xpanes/locale/xpanes.eo.tr
Labels: Translation
