Repository luanti-org/minetest_game, pull requests merged in 2024-06, with the labels that each got.

#3123 Fix large_cactus (upside down nodes)
  mods/default/schematics/large_cactus.mts
  schematic_tables.txt
Labels: One approval, Trivial, Bugfix

#3130 Avoid using the global keyword table as a function argument name
  mods/default/functions.lua
Labels: >= Two approvals, Trivial

#3132 Fix crafting for fences etc. starting with colon
  game_api.txt
  mods/default/functions.lua
Labels: One approval, Bugfix

#3129 Fix the possibility to put fire in a protected area
  mods/fire/init.lua
Labels: One approval, Trivial, Bugfix

#3131 Added can_grow function to plant definition
  game_api.txt
  mods/farming/api.lua
Labels: One approval

#3138 Replace deprecated `meta:set_string()` call
  mods/default/chests.lua
Labels: Trivial, Bugfix
