Repository luanti-org/minetest_game, pull requests merged in 2024-08, with the labels that each got.

#3150 Simplify and fix docker test
  utils/test/run.sh
  utils/test/world.mt
Labels: Maintenance

#3146 Fix crash if bones punched by non-player
  mods/bones/init.lua
Labels: >= Two approvals

#3125 Simplify Butterfly and Firefly codes
  mods/butterflies/init.lua
  mods/fireflies/init.lua
Labels: >= Two approvals, Maintenance
