Repository luanti-org/minetest_game, pull requests merged in 2025-06, with the labels that each got.

#3200 Beds: Add support for pova and player_monoids
  .luacheckrc
  mods/beds/functions.lua
  mods/beds/mod.conf
Labels: Bugfix

#3202 Redo bucket foreign namespace registration fix
  game_api.txt
  mods/bucket/init.lua
Labels: One approval, Bugfix

#3195 added Basque translation
  mods/beds/locale/beds.eu.tr
  mods/binoculars/locale/binoculars.eu.tr
  mods/boats/locale/boats.eu.tr
  mods/bones/locale/bones.eu.tr
  mods/bucket/locale/bucket.eu.tr
  mods/butterflies/locale/butterflies.eu.tr
  mods/carts/locale/carts.eu.tr
  mods/creative/locale/creative.eu.tr
  mods/default/locale/default.eu.tr
  mods/doors/locale/doors.eu.tr
  mods/dye/locale/dye.eu.tr
  mods/farming/locale/farming.eu.tr
  mods/fire/locale/fire.eu.tr
  mods/fireflies/locale/fireflies.eu.tr
  mods/flowers/locale/flowers.eu.tr
  mods/game_commands/locale/game_commands.eu.tr
  mods/keys/locale/keys.eu.tr
  mods/map/locale/map.eu.tr
  mods/mtg_craftguide/locale/mtg_craftguide.eu.tr
  mods/screwdriver/locale/screwdriver.eu.tr
  mods/sethome/locale/sethome.eu.tr
  mods/sfinv/locale/sfinv.eu.tr
  mods/stairs/locale/stairs.eu.tr
  mods/tnt/locale/tnt.eu.tr
  mods/vessels/locale/vessels.eu.tr
  mods/walls/locale/walls.eu.tr
  mods/wool/locale/wool.eu.tr
  mods/xpanes/locale/xpanes.eu.tr
Labels: One approval, Translation
