Repository luanti-org/minetest_game, pull requests merged in 2025-01, with the labels that each got.

#3177 Add safety checks before overriding builtin item entity
  mods/default/item_entity.lua
Labels: One approval, Maintenance

#3173 Beds: allow digging stray top nodes
  .luacheckrc
  mods/beds/api.lua
Labels: One approval, Bugfix

#3180 Fix TNT explosions not removing metadata
  mods/tnt/init.lua
Labels: Bugfix
